#!/usr/bin/env python3
"""
Analyze prompt generation data from promptGenPackage/
"""
import json
import os
from collections import defaultdict, Counter
import glob

def analyze_prompt_generation_data():
    """Analyze the prompt generation data and answer the user's questions."""
    
    # Directory paths for each LLM
    base_path = "/home/fanlgrp/Documents/zhiychen/LLM-poison/promptGenPackage"
    llm_dirs = {
        "gpt-4o": os.path.join(base_path, "azure_gpt-4o", "results"),
        "gpt-4o-mini": os.path.join(base_path, "azure_gpt-4o-mini", "results"),
        "llama": os.path.join(base_path, "openrouter_meta-llama_llama-4-scout", "results")
    }
    
    # Data structures to collect information
    all_urls_with_visible_text = set()  # URLs that have visible text (length > 0)
    prompts_by_llm = defaultdict(int)   # Count prompts by LLM
    url_prompt_counts = defaultdict(int)  # Count prompts per URL
    url_visible_text = {}  # Store visible text info for each URL
    
    print("Analyzing prompt generation data...")
    
    # Process each LLM directory
    for llm_name, results_dir in llm_dirs.items():
        if not os.path.exists(results_dir):
            print(f"Warning: Directory {results_dir} not found")
            continue
            
        print(f"\nProcessing {llm_name} data from {results_dir}")
        
        # Get all JSON files in the results directory
        json_files = glob.glob(os.path.join(results_dir, "*.json"))
        print(f"Found {len(json_files)} JSON files for {llm_name}")
        
        files_processed = 0
        total_entries = 0
        
        for json_file in json_files:
            try:
                with open(json_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    
                if not isinstance(data, list):
                    print(f"Warning: {json_file} does not contain a list")
                    continue
                    
                files_processed += 1
                total_entries += len(data)
                
                for entry in data:
                    url = entry.get('url', '')
                    visible_text_length = entry.get('visible_text_length', 0)
                    prompts_count = entry.get('prompts_count', 0)
                    success = entry.get('success', False)
                    
                    if not success:
                        continue
                        
                    # Count prompts by LLM
                    prompts_by_llm[llm_name] += prompts_count
                    
                    # Track URLs with visible text
                    if visible_text_length > 0:
                        all_urls_with_visible_text.add(url)
                        url_prompt_counts[url] += prompts_count
                        
                        # Store visible text info
                        if url not in url_visible_text:
                            url_visible_text[url] = {
                                'length': visible_text_length,
                                'preview': entry.get('visible_text_preview', '')
                            }
                            
            except Exception as e:
                print(f"Error processing {json_file}: {e}")
                continue
                
        print(f"Processed {files_processed} files with {total_entries} total entries for {llm_name}")
    
    # Calculate results
    unique_urls_with_visible_text = len(all_urls_with_visible_text)
    total_prompts = sum(prompts_by_llm.values())
    
    # Calculate average prompts per URL with visible text
    if unique_urls_with_visible_text > 0:
        avg_prompts_per_url = sum(url_prompt_counts.values()) / unique_urls_with_visible_text
    else:
        avg_prompts_per_url = 0
    
    # Print results
    print("\n" + "="*60)
    print("ANALYSIS RESULTS")
    print("="*60)
    
    print(f"\n1. UNIQUE URLs WITH VISIBLE TEXT: {unique_urls_with_visible_text}")
    
    print(f"\n2. PROMPTS GENERATED BY EACH LLM:")
    for llm_name, count in prompts_by_llm.items():
        print(f"   - {llm_name}: {count:,} prompts")
    print(f"   - Total: {total_prompts:,} prompts")
    
    print(f"\n3. AVERAGE PROMPTS PER UNIQUE URL WITH VISIBLE TEXT: {avg_prompts_per_url:.2f}")
    
    # Additional statistics
    print(f"\n4. ADDITIONAL STATISTICS:")
    print(f"   - URLs that generated prompts: {len(url_prompt_counts)}")
    
    # Show distribution of prompts per URL
    prompt_counts = list(url_prompt_counts.values())
    if prompt_counts:
        print(f"   - Min prompts per URL: {min(prompt_counts)}")
        print(f"   - Max prompts per URL: {max(prompt_counts)}")
        print(f"   - Median prompts per URL: {sorted(prompt_counts)[len(prompt_counts)//2]}")
    
    # Show top URLs by prompt count
    print(f"\n5. TOP 10 URLs BY PROMPT COUNT:")
    top_urls = sorted(url_prompt_counts.items(), key=lambda x: x[1], reverse=True)[:10]
    for i, (url, count) in enumerate(top_urls, 1):
        visible_length = url_visible_text.get(url, {}).get('length', 0)
        print(f"   {i:2d}. {url}")
        print(f"       Prompts: {count}, Visible text length: {visible_length}")
    
    return {
        'unique_urls_with_visible_text': unique_urls_with_visible_text,
        'prompts_by_llm': dict(prompts_by_llm),
        'avg_prompts_per_url': avg_prompts_per_url,
        'total_prompts': total_prompts,
        'urls_with_prompts': len(url_prompt_counts)
    }

if __name__ == "__main__":
    results = analyze_prompt_generation_data()
